name: Auto PR

on:
  push:
    branches:
      - 'release/*'

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request to the next higher release

        run: |
          BRANCHES=$(git branch -r | grep 'release/' | cut -d '/' -f 3 | sort -V)
          echo ${GITHUB_REF}
          exit 1
          # gh pr create -B main -H beef9999/minor-02 --title 'Merge' --body 'Created by Github action'