name: Auto Create Pull Request

on:
  push:
    branches:
      - 'beef9999/minor-01'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Create Pull Request
        run: gh pr create -B main -H beef9999/minor02 --title 'Merge' --body 'Created by Github action'