name: Auto Create Pull Request

on:
  push:
    branches:
      - 'beef9999/*'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install git

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: rpc-perf
          base: master